---

# Docker compose VS Code development file
version: '3.3'

services:

  python-development-container:
    build:
      context: ./docker
    restart: "no"
    volumes:
      ## Mount the development container to /code
      - ..:/code
      ## Mount a volume containing the VS code extensions to prevent having to install them each rebuild
      ## A volume will be created for both VS Code and VS Code Insiders edition
      - python-development-container-ext:/home/vscode/.vscode-server
      - python-development-container-ext-insiders:/home/vscode/.vscode-server-insiders
    tty: true

## Define the named volumes that are used for the above services
volumes:
  python-development-container-ext:
  python-development-container-ext-insiders: