---

# Common build setup for Ansible containers
.build-ansible:
  extends: .build-common
  variables:
    DOCKER_PATH: "./ansible/"
    IMAGE_TAG: "${CI_REGISTRY_IMAGE}/ansible"

# Build Ansible container for Ubuntu Noble
Build Ansible - Noble:
  extends: .build-ansible
  needs:
    - Build Base - Noble
  variables:
    RELEASE: noble
  script:
    - !reference [.build-common, script]
    - docker tag "${IMAGE_TAG}/${RELEASE}:${CI_COMMIT_SHORT_SHA}" "${IMAGE_TAG}:latest"
    - docker push "${IMAGE_TAG}:latest"
