---

# Common build setup for base containers
.build-base:
  extends: .build-common
  variables:
    DOCKER_PATH: "./base/"
    IMAGE_TAG: "${CI_REGISTRY_IMAGE}/base"

# Build base container for Ubuntu Jammy
Build Base - Jammy:
  extends: .build-base
  variables:
    RELEASE: jammy

# Build base container for Ubuntu Lunar
Build Base - Lunar:
  extends: .build-base
  variables:
    RELEASE: lunar
  script:
    - !reference [.build-common, script]
    - docker tag "${IMAGE_TAG}/${RELEASE}:${CI_COMMIT_SHORT_SHA}" "${IMAGE_TAG}:latest"
    - docker push "${IMAGE_TAG}:latest"
