---

# Common build setup for Django containers
.build-django:
  extends: .build-common
  variables:
    DOCKER_PATH: "./django/"
    IMAGE_TAG: "${CI_REGISTRY_IMAGE}/django"

# Build Django container for Ubuntu Jammy
Build Django - Jammy:
  extends: .build-django
  needs:
    - Build Python - Jammy
  variables:
    RELEASE: jammy

# Build Django container for Ubuntu Mantic
Build Django - Mantic:
  extends: .build-django
  needs:
    - Build Python - Mantic
  variables:
    RELEASE: mantic
  script:
    - !reference [.build-common, script]
    - docker tag "${IMAGE_TAG}/${RELEASE}:${CI_COMMIT_SHORT_SHA}" "${IMAGE_TAG}:latest"
    - docker push "${IMAGE_TAG}:latest"
