---

# Common build setup for Puppet containers
.build-puppet:
  extends: .build-common
  variables:
    DOCKER_PATH: "./puppet/"
    IMAGE_TAG: "${CI_REGISTRY_IMAGE}/puppet"

# Build Puppet container for Ubuntu Noble
Build Puppet - Noble:
  extends: .build-puppet
  needs:
    - Build Ruby - Noble
  variables:
    RELEASE: noble
  script:
    - !reference [.build-common, script]
    - docker tag "${IMAGE_TAG}/${RELEASE}:${CI_COMMIT_SHORT_SHA}" "${IMAGE_TAG}:latest"
    - docker push "${IMAGE_TAG}:latest"
