---

# Common build setup for Python containers
.build-python:
  extends: .build-common
  variables:
    DOCKER_PATH: "./python/"
    IMAGE_TAG: "${CI_REGISTRY_IMAGE}/python"

# Build Python container for Ubuntu Jammy
Build Python - Jammy:
  extends: .build-python
  needs:
    - Build Base - Jammy
  variables:
    RELEASE: jammy

# Build Python container for Ubuntu Lunar
Build Python - Lunar:
  extends: .build-python
  needs:
    - Build Base - Lunar
  variables:
    RELEASE: lunar
    PIP_OPTIONS: "--break-system-packages"
  script:
    - !reference [.build-common, script]
    - docker tag "${IMAGE_TAG}/${RELEASE}:${CI_COMMIT_SHORT_SHA}" "${IMAGE_TAG}:latest"
    - docker push "${IMAGE_TAG}:latest"
