---

# Common build setup for Ruby containers
.build-ruby:
  extends: .build-common
  variables:
    DOCKER_PATH: "./ruby/"
    IMAGE_TAG: "${CI_REGISTRY_IMAGE}/ruby"

# Build Ruby container for Ubuntu Noble
Build Ruby - Noble:
  extends: .build-ruby
  needs:
    - Build Base - Noble
  variables:
    RELEASE: noble
  script:
    - !reference [.build-common, script]
    - docker tag "${IMAGE_TAG}/${RELEASE}:${CI_COMMIT_SHORT_SHA}" "${IMAGE_TAG}:latest"
    - docker push "${IMAGE_TAG}:latest"
