## Base on base dev container which already includes node
FROM registry.gitlab.com/development-images/ubuntu/base:latest

## A mirror of the container is available at this alternative registry:
#FROM mirror.remote.sx/development-images/ubuntu/base:latest

## Set the work directory
WORKDIR /code