## Base on Ruby dev container
FROM registry.gitlab.com/development-images/ubuntu/ruby:latest

## A mirror of the container is available at this alternative registry:
#FROM registry.remote.sx/development-images/ubuntu/ruby:latest

## Set the work directory
WORKDIR /code