## Base on Ansible dev container
FROM registry.gitlab.com/development-images/ubuntu/ansible:latest

## A mirror of the container is available at this alternative registry:
#FROM registry.remote.sx/development-images/ubuntu/ansible:latest

## Set the work directory
WORKDIR /code